owner: Matungos
repo: upptime

sites:
  - name: IM API
    url: https://api.montevideo.gub.uy/transporteRest/variantes/3873

status-website:
  cname: uptime.matungos.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: im api uptime
  introTitle: ""
  introMessage: Esta página se actualiza cada 5 minutos.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

git:
  pullBeforePush: true
